DROP DATABASE IF EXISTS PROG_OBJ_DB_PROVA2;
CREATE DATABASE IF NOT EXISTS PROG_OBJ_DB_PROVA2;
USE PROG_OBJ_DB_PROVA2;

DROP TABLE IF EXISTS prof_table;
CREATE TABLE prof_table
(
	COD_PROF INT AUTO_INCREMENT,
	NOME_PROF VARCHAR(50) NOT NULL,
	PRIMARY KEY(COD_PROF)
);

INSERT INTO prof_table(NOME_PROF)
	VALUES('Cleiton Rasta');
	
DROP TABLE IF EXISTS aula_table;
CREATE TABLE aula_table
(
	COD_AULA INT AUTO_INCREMENT,
	NOME_AULA VARCHAR(50) NOT NULL,
	DESC_AULA VARCHAR(600),
	COD_PROF INT,
	CONSTRAINT fk_aula_prof
	FOREIGN KEY (COD_PROF)
	REFERENCES prof_table(COD_PROF),
	PRIMARY KEY(COD_AULA)
);

INSERT INTO aula_table(NOME_AULA, DESC_AULA, COD_PROF)
	VALUES('Aula de musica', 'Aulas sobre o teorema da sinfonia e organização musical.', null);